"""
perceptrome_web_cli.py

Run a small web server that serves the built Vite/TypeScript client and exposes
a WebSocket endpoint for controlling Perceptrome from the browser.

Project layout (expected):

perceptrome_web/
├─ perceptrome_web_cli.py        # this file
└─ client/
   ├─ package.json
   ├─ vite.config.ts
   ├─ src/
   └─ dist/                      # generated by: npm run build

Usage:

    python perceptrome_web_cli.py --host 0.0.0.0 --port 8000

Then open http://localhost:8000 in your browser.

Protocol (WS /ws):

- Client → Server (first message):
    {
        "type": "start_run",
        "config": { ... arbitrary JSON config ... }
    }

- Server → Client messages:
    { "type": "status", "status": "pending|running|done|error", "progress": 0.0-1.0? }
    { "type": "log",    "message": "human readable line" }
    { "type": "result", "payload": { ... final result JSON ... } }

The demo implementation simulates a Perceptrome run with dummy progress and a
fake result. Replace `simulate_perceptrome_run` with a call into your real code.
"""

from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path
from typing import Any, Dict

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.staticfiles import StaticFiles
import uvicorn


# ---------------------------------------------------------------------------
# Configuration / paths
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parent
DEFAULT_STATIC_DIR = ROOT_DIR / "client" / "dist"


def ensure_static_dir(static_dir: Path) -> Path:
    """
    Ensure that the static directory exists and looks like a Vite build output.
    Raise a clear error if not, so the CLI fails loudly instead of 404'ing.
    """
    if not static_dir.exists():
        raise SystemExit(
            f"[perceptrome_web] client build not found: {static_dir}\n"
            "You probably need to run:\n\n"
            "    cd client\n"
            "    npm install\n"
            "    npm run build\n"
        )

    index_file = static_dir / "index.html"
    if not index_file.is_file():
        raise SystemExit(
            f"[perceptrome_web] {static_dir} exists but index.html is missing.\n"
            "Make sure your Vite build output is in client/dist."
        )

    return static_dir


# ---------------------------------------------------------------------------
# Fake Perceptrome integration (to be replaced with real logic)
# ---------------------------------------------------------------------------

async def simulate_perceptrome_run(config: Dict[str, Any], ws: WebSocket) -> Dict[str, Any]:
    """
    Simulated Perceptrome job.

    - Sends periodic status and log messages over the WebSocket.
    - Returns a final "result" dict that will be sent as a `result` message.

    Replace this with your *real* Perceptrome invocation, e.g.:

        from perceptrome import run_experiment

        def run_perceptrome(config):
            return run_experiment(**config)

    and then adapt this coroutine to call it (possibly via run_in_executor).
    """
    await ws.send_json({"type": "status", "status": "running", "progress": 0.0})
    await ws.send_json({
        "type": "log",
        "message": f"Starting Perceptrome run with config: {json.dumps(config)}",
    })

    # fake 10 steps of work
    steps = 10
    for step in range(1, steps + 1):
        # simulate some work
        await asyncio.sleep(0.4)

        progress = step / steps
        await ws.send_json({
            "type": "status",
            "status": "running",
            "progress": progress,
        })
        await ws.send_json({
            "type": "log",
            "message": f"Step {step}/{steps} completed (progress={progress:.0%})",
        })

    # fake "result"
    result: Dict[str, Any] = {
        "summary": "Perceptrome run completed successfully.",
        "config_echo": config,
        "metrics": {
            "example_metric": 0.987,
            "another_metric": 42,
        },
    }

    await ws.send_json({
        "type": "log",
        "message": "Perceptrome run finished. Preparing result payload…",
    })

    await ws.send_json({
        "type": "status",
        "status": "done",
        "progress": 1.0,
    })

    return result


# ---------------------------------------------------------------------------
# FastAPI app + WebSocket endpoint
# ---------------------------------------------------------------------------

def create_app(static_dir: Path) -> FastAPI:
    """
    Create and configure the FastAPI app, mounting the static frontend and
    defining the WebSocket endpoint for Perceptrome runs.
    """
    app = FastAPI(title="Perceptrome Web")

    # Serve the Vite build (index.html + assets) from /
    app.mount(
        "/",
        StaticFiles(directory=static_dir, html=True),
        name="static",
    )

    @app.websocket("/ws")
    async def perceptrome_ws(ws: WebSocket) -> None:
        """
        WebSocket endpoint for controlling Perceptrome.

        Expected first message:
            {"type": "start_run", "config": {...}}

        Sends back:
            - status updates
            - log messages
            - final result
        """
        await ws.accept()

        try:
            # Receive the first message (must be a "start_run")
            first_msg = await ws.receive_text()
            try:
                data = json.loads(first_msg)
            except json.JSONDecodeError:
                await ws.send_json({
                    "type": "log",
                    "message": "Error: first message must be valid JSON.",
                })
                await ws.send_json({
                    "type": "status",
                    "status": "error",
                    "progress": None,
                })
                await ws.close()
                return

            msg_type = data.get("type")
            if msg_type != "start_run":
                await ws.send_json({
                    "type": "log",
                    "message": "Error: expected message.type == 'start_run'.",
                })
                await ws.send_json({
                    "type": "status",
                    "status": "error",
                    "progress": None,
                })
                await ws.close()
                return

            config = data.get("config") or {}
            if not isinstance(config, dict):
                await ws.send_json({
                    "type": "log",
                    "message": "Error: 'config' must be an object.",
                })
                await ws.send_json({
                    "type": "status",
                    "status": "error",
                    "progress": None,
                })
                await ws.close()
                return

            # At this point, we have a valid config — run Perceptrome
            try:
                result = await simulate_perceptrome_run(config, ws)
            except Exception as e:  # pylint: disable=broad-except
                await ws.send_json({
                    "type": "log",
                    "message": f"Perceptrome run failed: {e!r}",
                })
                await ws.send_json({
                    "type": "status",
                    "status": "error",
                    "progress": None,
                })
                await ws.close()
                return

            # Send final result payload
            await ws.send_json({
                "type": "result",
                "payload": result,
            })

            await ws.close()

        except WebSocketDisconnect:
            # Client disconnected mid-run — just stop.
            # If you add real Perceptrome runs, you may want to add cancellation here.
            return

    return app


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Serve the Perceptrome web UI and WebSocket API."
    )
    parser.add_argument(
        "--host",
        type=str,
        default="127.0.0.1",
        help="Host interface to bind (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="TCP port to bind (default: 8000)",
    )
    parser.add_argument(
        "--static-dir",
        type=str,
        default=str(DEFAULT_STATIC_DIR),
        help="Path to the built client/dist directory (default: client/dist)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    static_dir = ensure_static_dir(Path(args.static_dir))
    app = create_app(static_dir)

    # Run Uvicorn with the in-memory app instance
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_level="info",
    )


# Uvicorn compatibility: allow `uvicorn perceptrome_web_cli:app` as well.
# We create a default app using the DEFAULT_STATIC_DIR, but this will raise
# a clear error if the client has not been built yet.
try:
    _default_static_dir = ensure_static_dir(DEFAULT_STATIC_DIR)
    app = create_app(_default_static_dir)
except SystemExit:
    # If the static dir is missing at import time, we still want the CLI
    # (`python perceptrome_web_cli.py`) to give a helpful error, but we
    # don't want importing this module to crash tools. So just create a
    # minimal app that 404s everything; the CLI path will re-check dirs.
    app = FastAPI(title="Perceptrome Web (no static build found)")


if __name__ == "__main__":
    main()
